"""empty message

Revision ID: a78a3b57a169
Revises: e61f313fad02
Create Date: 2019-11-13 11:07:08.586766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78a3b57a169'
down_revision = 'e61f313fad02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videographer_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['videographer_id'], ['videographer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Video')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Video',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Video_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('videographer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['videographer_id'], ['videographer.id'], name='Video_videographer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Video_pkey')
    )
    op.drop_table('video')
    # ### end Alembic commands ###
