"""empty message

Revision ID: c676e8b440e4
Revises: 
Create Date: 2019-11-19 16:06:17.908790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'c676e8b440e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('videographer', sa.Column('created_by', sa.String(), nullable=False, server_default="error"))

    op.alter_column('videographer', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('videographer', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videographer', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('videographer', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('videographer', 'created_by')
    # ### end Alembic commands ###
